class Point:
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...
    def addr(self) -> int: ...

class State:
    position: Point
    orientation: float
    velocity: float
    time: int
    def __init__(self, position: Point, orientation: float, velocity: float, time: int) -> None: ...
    def addr(self) -> int: ...

def add(a: Point, b: Point) -> Point: ...
