[build-system]
requires = ["scikit-build-core", "cffi"]
build-backend = "scikit_build_core.build"

[project]
name = "c-core-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "cffi>=2.0.0",
    "setuptools>=82.0.1",
]
